version: '3'
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - planning_poker_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:${REDIS_PORT}"
    networks:
      - planning_poker_network

networks:
  planning_poker_network:
    driver: bridge

volumes:
  postgres_data: