version: '3'
services:
  postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - planning_poker_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - planning_poker_network

networks:
  planning_poker_network:
    driver: bridge

volumes:
  postgres_data: