version: '3'
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - planning_poker_network

  test-postgres:
    image: postgres:16-alpine
    ports:
      - "${TEST_POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${TEST_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TEST_POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_POSTGRES_DB}
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    networks:
      - planning_poker_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:${REDIS_PORT}"
    networks:
      - planning_poker_network

networks:
  planning_poker_network:
    driver: bridge

volumes:
  postgres_data:
  postgres_test_data: